apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: vairavarumu/deploy-test:v5
        command: ["sleep", "9999"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: NodePort
  selector:
    app: python
  ports:
  - protocol: TCP
    port: 80          # Service port
    targetPort: 80    # Container port
    nodePort: 30090   # NodePort (choose any port between 30000-32767)

