apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python
  name: python-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - command:
        - sleep
        - '9999'
        image: mysql:8.0
        name: python
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  ports:
  - nodePort: 30090
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: python
  type: NodePort
